### ISSUE TITLE
Callback is triggered immediately

### ISSUE THREAD

**Issue by drdreo** [chukwumaijem/roll-a-die#5]
The provided callback will be executed immediately. It would be great if it is executed after the animation faded.

`rollADie({
            element,
            numberOfDice: 1,
            delay: 3000,
            callback: () => {
                console.log("done animating");
            },
            values: [value]
        });`

**Comment by chukwumaijem** [comment]
Hey @drdreo, you should be able to do this in your callback with a setTimeout.

**Comment by drdreo** [comment]
Yeah, i forked it and implemented it to return a Promise.
